base_url = "https://ourmachinery.github.io/themachinery-books/the_machinery_book/"
tutorials = "https://ourmachinery.github.io/themachinery-books/tutorials/"
the_machinery_book = "https://ourmachinery.github.io/themachinery-books/the_machinery_book/" 
docs = "https://ourmachinery.com/apidoc/"